---

- name: Base setup for all servers
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true


    - name: Install base packages
      apt:
        name:
          - vim
          - curl
          - net-tools
        state: present
